/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./components/header/Banner.vue')['default']
    BidRecord: typeof import('./components/goods-detail/BidRecord.vue')['default']
    BidRecordCard: typeof import('./components/goods-detail/BidRecordCard.vue')['default']
    BidRecordItem: typeof import('./components/goods-detail/BidRecordItem.vue')['default']
    BidRecordList: typeof import('./components/goods-detail/BidRecordList.vue')['default']
    BidRecordListItem: typeof import('./components/goods-detail/BidRecordListItem.vue')['default']
    CategoryCard: typeof import('./components/swiper-floor/CategoryCard.vue')['default']
    ContainerBox: typeof import('./components/ContainerBox.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    GoodsCard: typeof import('./components/goods-floor/GoodsCard.vue')['default']
    GoodsFloor: typeof import('./components/goods-floor/GoodsFloor.vue')['default']
    GoodsItem: typeof import('./components/goods-floor/GoodsItem.vue')['default']
    HeaderBar: typeof import('./components/header/HeaderBar.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HotGoodsItem: typeof import('./components/goods-detail/HotGoodsItem.vue')['default']
    HotGoodsList: typeof import('./components/goods-detail/HotGoodsList.vue')['default']
    MessageBox: typeof import('./components/MessageBox.vue')['default']
    NutAvatar: typeof import('@nutui/nutui')['Avatar']
    NutBacktop: typeof import('@nutui/nutui')['Backtop']
    NutCountdown: typeof import('@nutui/nutui')['Countdown']
    NutInfiniteLoading: typeof import('@nutui/nutui')['InfiniteLoading']
    NutPrice: typeof import('@nutui/nutui')['Price']
    NutStep: typeof import('@nutui/nutui')['Step']
    NutSteps: typeof import('@nutui/nutui')['Steps']
    NutSwiper: typeof import('@nutui/nutui')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui')['SwiperItem']
    NutTabPane: typeof import('@nutui/nutui')['TabPane']
    NutTabs: typeof import('@nutui/nutui')['Tabs']
    PersonBox: typeof import('./components/PersonBox.vue')['default']
    PrimaryButton: typeof import('./components/PrimaryButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    ShadowCard: typeof import('./components/ShadowCard.vue')['default']
    SwiperCard: typeof import('./components/swiper-floor/SwiperCard.vue')['default']
    SwiperFloor: typeof import('./components/swiper-floor/SwiperFloor.vue')['default']
    TabMenu: typeof import('./components/header/tabmenu/TabMenu.vue')['default']
    TabMenuItem: typeof import('./components/header/tabmenu/TabMenuItem.vue')['default']
    TopBar: typeof import('./components/header/topbar/TopBar.vue')['default']
    TopBarItem: typeof import('./components/header/topbar/TopBarItem.vue')['default']
    UserCenterCard: typeof import('./components/swiper-floor/UserCenterCard.vue')['default']
    Waterfall: typeof import('./components/Waterfall.vue')['default']
  }
}
