/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./components/header/Banner.vue')['default']
    CategoryCard: typeof import('./components/swiper-floor/CategoryCard.vue')['default']
    ContainerBox: typeof import('./components/ContainerBox.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Floor: typeof import('./components/swiper-floor/Floor.vue')['default']
    GoodsCard: typeof import('./components/goods-floor/GoodsCard.vue')['default']
    GoodsFloor: typeof import('./components/goods-floor/GoodsFloor.vue')['default']
    GoodsItem: typeof import('./components/goods-floor/GoodsItem.vue')['default']
    Header: typeof import('./components/header/Header.vue')['default']
    HeaderBar: typeof import('./components/header/HeaderBar.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MessageBox: typeof import('./components/MessageBox.vue')['default']
    NutAvatar: typeof import('@nutui/nutui')['Avatar']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutCol: typeof import('@nutui/nutui')['Col']
    NutInput: typeof import('@nutui/nutui')['Input']
    NutPrice: typeof import('@nutui/nutui')['Price']
    NutRow: typeof import('@nutui/nutui')['Row']
    NutSwiper: typeof import('@nutui/nutui')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui')['SwiperItem']
    PersonBox: typeof import('./components/PersonBox.vue')['default']
    PrimaryButton: typeof import('./components/PrimaryButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    ShadowCard: typeof import('./components/ShadowCard.vue')['default']
    SwiperCard: typeof import('./components/swiper-floor/SwiperCard.vue')['default']
    SwiperFloor: typeof import('./components/swiper-floor/SwiperFloor.vue')['default']
    TabBar: typeof import('./components/index/tabbar/TabBar.vue')['default']
    TabBarItem: typeof import('./components/index/tabbar/TabBarItem.vue')['default']
    TabMenu: typeof import('./components/header/tabmenu/TabMenu.vue')['default']
    TabMenuItem: typeof import('./components/header/tabmenu/TabMenuItem.vue')['default']
    TopBar: typeof import('./components/header/topbar/TopBar.vue')['default']
    TopBarItem: typeof import('./components/header/topbar/TopBarItem.vue')['default']
    UserCenterCard: typeof import('./components/swiper-floor/UserCenterCard.vue')['default']
  }
}
